# ███████╗███╗░░░███╗██████╗░███████╗░██████╗████████╗██████╗░██╗░█████╗░████████╗
# ██╔════╝████╗░████║██╔══██╗██╔════╝██╔════╝╚══██╔══╝██╔══██╗██║██╔══██╗╚══██╔══╝
# █████╗░░██╔████╔██║██████╔╝█████╗░░╚█████╗░░░░██║░░░██████╔╝██║██║░░╚═╝░░░██║░░░
# ██╔══╝░░██║╚██╔╝██║██╔══██╗██╔══╝░░░╚═══██╗░░░██║░░░██╔══██╗██║██║░░██╗░░░██║░░░
# ██║░░░░░██║░╚═╝░██║██║░░██║███████╗██████╔╝░░░██║░░░██║░░██║██║╚█████╔╝░░░██║░░░
# ╚═╝░░░░░╚═╝░░░░░╚═╝╚═╝░░╚═╝╚══════╝╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝╚═╝░╚════╝░░░░╚═╝░░░
# Связь с разработчиком:
# VK - @feymer31
# TG - @feymerwtf
settings:
  cooldown-message: 1 # Задержка на сообщения (в секундах)
  flight-mode:
    pickup-items: true # Запретить подбирать ресурсы во флае?
    block-place: true # Запретить ставить блоки во флае?
    block-break: true # Запретить ломать блоки во флае?
    block-commands: true # Запретить использовать запрещенные команды во флае?
    chest-open: true # Запретить открывать сундуки во флае?
    enderchest-open: true # Запретить открывать эндер-сундуки во флае?
    shulker-open: true # Запретить открывать шалкера во флае?
    crystal-interact: true # Запретить взаимодействовать с энд-кристаллом во флае?
    bow-interact: true # Запретить взаимодействовать с луком во флае?
  god-mode:
    pickup-items: true # Запретить подбирать ресурсы в режиме бога?
    block-place: true # Запретить ставить блоки в режиме бога?
    block-break: true # Запретить ломать блоки в режиме бога?
    block-commands: true # Запретить использовать запрещенные команды в режиме бессмертия?
    chest-open: true # Запретить открывать сундуки в режиме бессмертия?
    enderchest-open: true # Запретить открывать эндер-сундуки в режиме бессмертия?
    shulker-open: true # Запретить открывать шалкера в режиме бессмертия?
    crystal-interact: true # Запретить взаимодействовать с энд-кристаллом в режиме бессмертия?
    bow-interact: true # Запретить взаимодействовать с луком в режиме бессмертия?
  vanish:
    pickup-items: true # Запретить подбирать ресурсы в ванише?
    block-place: true # Запретить ставить блоки в ванише?
    block-break: true # Запретить ломать блоки в ванише?
    block-commands: true # Запретить использовать запрещенные команды в ванише?
    chest-open: true # Запретить открывать сундуки в ванише?
    enderchest-open: true # Запретить открывать эндер-сундуки в ванише?
    shulker-open: true # Запретить открывать шалкера в ванише?
    crystal-interact: true # Запретить взаимодействовать с энд-кристаллом в ванише?
    bow-interact: true # Запретить взаимодействовать с луком в ванише?
  walk-speed:
    pickup-items: true # Запретить подбирать ресурсы с большой скоростью?
    block-place: true # Запретить ставить блоки с большой скоростью?
    block-break: true # Запретить ломать блоки с большой скоростью?
    block-commands: true # Запретить использовать запрещенные команды с большой скоростью?
    chest-open: true # Запретить открывать сундуки с большой скоростью?
    enderchest-open: true # Запретить открывать эндер-сундуки с большой скоростью?
    shulker-open: true # Запретить открывать шалкера с большой скоростью?
    crystal-interact: true # Запретить взаимодействовать с энд-кристаллом с большой скоростью?
    bow-interact: true # Запретить взаимодействовать с луком с большой скоростью?
  block-commands: # Запрещенные команды
    - "invsee"
messages:
  flight-mode:
    pickup-items: "&fВы не можете &aподбирать ресурсы &fво флае!" # Сообщение когда игрок подбирает ресурсы во флае
    block-place: "&fВы не можете &aставить блоки &fво флае!" # Сообщение, когда игрок ставит блоки во флае
    block-break: "&fВы не можете &aломать блоки &fво флае!" # Сообщение, когда игрок ломает блоки во флае
    block-commands: "&fВы не можете &aиспользовать &fэту команду во флае!" # Сообщение, когда игрок использует команду, которая запрещена во флае
    chest-open: "&fВы не можете &aоткрывать &fсундуки во флае!" # Сообщение, когда игрок открывает сундук во флае
    enderchest-open: "&fВы не можете &aоткрывать &fэндер-сундуки во флае!" # Сообщение, когда игрок открывает эндер-сундук во флае
    shulker-open: "&fВы не можете &aоткрывать &fшалкера во флае!" # Сообщение, когда игрок открывает шалкер во флае
    crystal-interact: "&fВы не можете &aвзаимодействовать &fс кристаллом во флае!" # Сообщение, когда игрок взаимодействует с кристаллом во флае
    bow-interact: "&fВы не можете &aвзаимодействовать &fс луком во флае!" # Сообщение, когда игрок взаимодействует с луком во флае
  god-mode:
    pickup-items: "&fВы не можете &aподбирать ресурсы &fв режиме бессмертия!" # Сообщение, когда игрок подбирает ресурсы в режиме бога
    block-place: "&fВы не можете &aставить блоки &fв режиме бессмертия!" # Сообщение, когда игрок ставит блоки в режиме бога
    block-break: "&fВы не можете &aломать блоки &fв режиме бессмертия!" # Сообщение, когда игрок ломает блоки в режиме бога
    block-commands: "&fВы не можете &aиспользовать &fэту команду в режиме бессмертия!" # Сообщение, когда игрок использует команду, которая запрещена в режиме бессмертия
    chest-open: "&fВы не можете &aоткрывать &fсундуки в режиме бессмертия!" # Сообщение, когда игрок открывает сундук в режиме бессмертия
    enderchest-open: "&fВы не можете &aоткрывать &fэндер-сундуки в режиме бессмертия!" # Сообщение, когда игрок открывает эндер-сундук в режиме бессмертия
    shulker-open: "&fВы не можете &aоткрывать &fшалкера в режиме бессмертия!" # Сообщение, когда игрок открывает шалкер в режиме бессмертия
    crystal-interact: "&fВы не можете &aвзаимодействовать &fс кристаллом в режиме бессмертия!" # Сообщение, когда игрок взаимодействует с кристаллом в режиме бессмертия
    bow-interact: "&fВы не можете &aвзаимодействовать &fс луком во флае!" # Сообщение, когда игрок взаимодействует с луком в режиме бессмертия
  vanish:
    pickup-items: "&fВы не можете &aподбирать ресурсы &fв режиме невидимости!" # Сообщение, когда игрок подбирает ресурсы в ванише
    block-place: "&fВы не можете &aставить блоки &fв режиме невидимости!" # Сообщение, когда игрок ставит блоки в ванише
    block-break: "&fВы не можете &aломать блоки &fв режиме невидимости!" # Сообщение, когда игрок ломает блоки в ванише
    block-commands: "&fВы не можете &aиспользовать &fэту команду в режиме невидимости!" # Сообщение, когда игрок использует команду, которая запрещена в режиме невидимости
    chest-open: "&fВы не можете &aоткрывать &fсундуки в режиме невидимости!" # Сообщение, когда игрок открывает сундук в режиме невидимсоти
    enderchest-open: "&fВы не можете &aоткрывать &fэндер-сундуки в режиме невидимости!" # Сообщение, когда игрок открывает эндер-сундук в режиме невидимости
    shulker-open: "&fВы не можете &aоткрывать &fшалкера в режиме невидимости!" # Сообщение, когда игрок открывает шалкер в режиме невидимости
    crystal-interact: "&fВы не можете &aвзаимодействовать &fс кристаллом в режиме невидимости!" # Сообщение, когда игрок взаимодействует с кристаллом в режиме невидимости
    bow-interact: "&fВы не можете &aвзаимодействовать &fс луком во флае!" # Сообщение, когда игрок взаимодействует с луком в невидимости
  walk-speed:
    pickup-items: "&fВы не можете &aподбирать ресурсы &fс большой скоростью!" # Сообщение, когда игрок подбирает ресурсы с большой скоростью
    block-place: "&fВы не можете &aставить блоки &fс большой скоростью!" # Сообщение, когда игрок ставит блоки с большой скоростью
    block-break: "&fВы не можете &aломать блоки &fс большой скоростью!" # Сообщение, когда игрок ломает блоки с большой скоростью
    block-commands: "&fВы не можете &aиспользовать &fэту команду с большой скоростью!" # Сообщение, когда игрок использует команду, которая запрещена с большой скоростью
    chest-open: "&fВы не можете &aоткрывать &fсундуки с большой скоростью!" # Сообщение, когда игрок открывает сундук с большой скоростью
    enderchest-open: "&fВы не можете &aоткрывать &fэндер-сундуки с большой скоростью!" # Сообщение, когда игрок открывает эндер-сундук с большой скоростью
    shulker-open: "&fВы не можете &aоткрывать &fшалкера с большой скоростью!" # Сообщение, когда игрок открывает шалкер с большой скоростью
    crystal-interact: "&fВы не можете &aвзаимодействовать &fс кристаллом с большой скоростью!" # Сообщение, когда игрок взаимодействует с кристаллом с большой скоростью
    bow-interact: "&fВы не можете &aвзаимодействовать &fс луком с большой скоростью!" # Сообщение, когда игрок взаимодействует с луком с большой скоростью
  commands:
    reload: "&fВы успешно &aперезагрузили &fплагин!" # Сообщение, когда плагин перезагружен
    no-permission: "&fУ Вас &c&nнедостаточно&f прав!" # Сообщение, когда у игрока не хватает прав
    no-args: "&fВведите &6/fmrestrict reload&f, чтобы перезагрузить плагин." # Сообщение, когда не хватает аргументов